### ISSUE TITLE
Refatorar código de acordo com novo diagrama de classes

### ISSUE THREAD

**Issue by erijonhson** [erijonhson/si1-disque-saude-backend#3]
Essa questão deve ser quebrada em partes, para cada estratégia indicada pelo [Diagrama de Classes](https://github.com/erijonhson/si1-disque-saude-backend/issues/2) e [Especificação](https://docs.google.com/document/d/1Vr9jAWIQ1-SmYOFpZt-WHwF1iRMspBnCMavr-chAgbs/pub), teremos uma microquestão para resolver.

**Comment by igorbrasileiro** [comment]
Precisa testar offline mesmo o BD se está funcionando corretamente.

**Comment by erijonhson** [comment]
Talvez ajude no BD: https://www.thoughts-on-java.org/many-relationships-additional-properties/

**Comment by erijonhson** [comment]
Questão de Criar ou Atualizar tupla no BD: https://stackoverflow.com/a/28428729

**Comment by erijonhson** [comment]
Entendendo @CrossOrigin e o tal do UriComponentsBuilder:
http://restlet.com/company/blog/2015/12/15/understanding-and-using-cors/

**Comment by erijonhson** [comment]
State Pattern para resolver Queixas: https://www.youtube.com/watch?v=zwqsWJodSpg

**Comment by erijonhson** [comment]
Não é mais importante que fazer os casos de uso, mas há como testar BD parecido com testes de unidade (sem container): http://arquillian.org/guides/testing_java_persistence_de/
Testes com Spring: http://arquillian.org/blog/tags/spring/

**Comment by erijonhson** [comment]
Já modificamos o model uma vez mais, então darei essa questão como finalizada.
